### ISSUE TITLE
No documentation available for integration with refinerycms-blog

### ISSUE THREAD

**Issue by kevinsmouts** [refinery/refinerycms-page-images#122]
Hello guys,

I come from [#206 on refinerycms-blog](https://github.com/refinery/refinerycms-blog/issues/206), where it has been refused to implement a feature to have a featured image field for each blog post. The reason for the refusal is that `refinerycms-page-images`already does that properly.

Great.

But there is **zero** documentation for it available here or on refinerycms-blog.

In my views when I call:
```ruby
<% @posts.each do |blog_post| %>
<%= blog_post.images.first.thumbnail.url %>
```

I get an `(undefined method 'thumbnail' for nil:NilClass)`

Now how are we supposed to do that? If I get an answer from someone, I can start figuring it out and edit the current documentation to a proper state.

**Comment by simi** [comment]
Hello. What is your setup?

I think the correct way how to add images to custom engine is:

1. follow https://github.com/refinery/refinerycms-page-images#install
2. edit page-images initializer (default values are here https://github.com/refinery/refinerycms-page-images/blob/master/lib/refinery/page_images/configuration.rb#L9-L15)
3. follow https://github.com/refinery/refinerycms-page-images#usage

For your example `blog_post.images` is empty array, so calling `first` there returns `nil`. You need to check if there is any image first to ensure that `images.first` returns actually an image instead of `nil`.

**Comment by kevinsmouts** [comment]
Indeed, `blog_post.images` returns an empty array even though I added images to the blog_post in the admin section, which I was trying to point out.

The reason I think, is because while images are set to belong to a polymorphic "page" (in that case a `Refinrey::Blog::Post`) nothing has been set at the class level for the blog post to consider itself with `has_many` images.

What you are pointing to with the initializer seems to be the admin tab with images for blog posts (which indeed works), but not the class level integration of `has_many` images, which would allow the use of `blog_post.images`

**Comment by kevinsmouts** [comment]
https://github.com/refinery/refinerycms-page-images/pull/127
